experiments:
  data:
    raster: /data/s2a_bb_20m
    vector: /data/ALKIS_bb_all_Nutzung
  workload:
    get:
      vector:
        - oid
      raster:
        - sval:
            aggregations:
              - avg
              - max
              - min
              - count
              - sum
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - oid
    order:
      vector:
        - oid
    condition:
      vector:
        - nutzart = 'Landwirtschaft'


  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - true
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster


  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    #- name: rasdaman
