experiments:
  data:
    raster: /data/wind_airdensity_10m
    vector: /data/wildfires_usa
  workload:
    get:
      vector:
        - FIRE_ID
      raster:
        - sval:
            aggregations:
              - count
              - min
              - max
              - avg
              - sum
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - FIRE_ID
    order:
      vector:
        - FIRE_ID
    extent:
      bbox:
        xmin: -111.86229098299998
        ymin: 39.08127330899998
        xmax: -105.19902193299998
        ymax: 49.04697127700001
        srid: 4269


  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - execution
    raster_clip:
      - false
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
      


  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    - name: rasdaman

