experiments:
  data:
    raster: /data/nlcd
    vector: /data/wildfires_usa
  workload:
    get:
      vector:
        - FIRE_ID
      raster:
        - sval
        - sval:
            aggregations:
              - count
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - FIRE_ID
      raster:
        - sval
    order:
      vector:
        - FIRE_ID
      raster:
        - sval

  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - false
    vector_filter_at_stage:
      - preprocess
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
      


  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    #- name: rasdaman
