experiments:
  data:
    raster: /data/wind_airdensity_10m
    vector: /data/coastline_2020
  workload:
    get:
      vector:
        - OBJECTID
      raster:
        - sval:
            aggregations:
              - count
              - sum
              - min
              - max
              - avg
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - OBJECTID
    order:
      vector:
        - OBJECTID

  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - false
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
    vector_simplify:
      # - 0
      # - 100
      # - 200
      # - 500
      # - 1000
      # - 2000
      # - 5000
      - 10000
      - 0.00001
      - 0.00005
      - 0.0001
      - 0.1
      - 1
      - 2
      - 5
      - 10
      - 20
      - 50
      


  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    #- name: rasdaman
