experiments:
  data:
    raster: /data/dem_us_div12
    vector: /data/wildfires_usa
  workload:
    get:
      vector:
        - FIRE_ID
      raster:
        - sval:
            aggregations:
              - avg
              - max
              - min
              - count
              - sum
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - FIRE_ID
    order:
      vector:
        - FIRE_ID

  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - false
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
    vector_simplify:
      # - 0
      # - 0.000001
      # - 0.000002
      # - 0.000005
      # - 0.00001
      # - 0.00002
      # - 0.00005
      # - 0.0001
      - 0.0002
      - 0.0005
      - 0.001
      - 0.002
      - 0.005



  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    # - name: rasdaman
