experiments:
  data:
    raster: /data/dem_us_div12
    vector: /data/amtrak_clean
  workload:
    get: 
      vector:
        - ref
      raster: 
        - sval:
            aggregations:
              - max
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector: 
        - ref
    order:
      vector: 
        - ref

  parameters:
    raster_tile_size:
      - auto
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - false
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
      


  timeout: 1000
  warm_starts: 3

  systems:
    - name: beast
    - name: postgis
    - name: rasdaman
