experiments:
  data:
    raster: /data/dem_us_div12
    vector: /data/amtrak_clean
  workload:
    get: 
      vector:
        - ref
      raster: 
        - sval:
            aggregations:
              - max
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector: 
        - ref
    order:
      vector: 
        - ref

  parameters:
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - true
      - false
    vector_filter_at_stage:
      - preprocess
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
    raster_tile_size:
      - 10x10
      - 20x20
      - 50x50
      - 70x70
      - 100x100
      - 200x200
      - 500x500
      - 700x700
      - 1000x1000
      - 2000x2000
      - 3000x3000
      - 5000x5000
      


  timeout: 1800
  warm_starts: 3

  systems:
    - name: postgis
