experiments:
  data:
    raster: /data/lulc_emilia
    vector: /data/landslides_emilia
  workload:
    get:
      vector:
        - id
      raster:
        - sval
        - sval:
            aggregations:
              - count
    join:
      table1: vector
      table2: raster
      condition: intersect(raster, vector)
    group:
      vector:
        - id
      raster:
        - sval
    order:
      vector:
        - id
      raster:
        - sval

  parameters:
    align_crs_at_stage:
      - preprocess
    raster_clip:
      - false
      - true
    vector_filter_at_stage:
      - execution
    vectorize_type:
      - polygons
    vectorize_format:
      - shp
    align_to_crs:
      - raster
    raster_tile_size:
      - 10x10
      - 20x20
      - 50x50
      - 70x70
      - 100x100
      - 200x200
      - 500x500
      - 700x700
      - 1000x1000
      - 2000x2000
      - 3000x3000
      - 5000x5000
      - 7000x7000
      - 10000x10000


  timeout: 3000
  warm_starts: 3

  systems:
    - name: postgis
